; Height of the HUD.
DEF HUD_HEIGHT EQU $14

; Coordinate for SCX when displaying HUD.
DEF HUD_SCX EQU $00

; Coordniate for SCY when displaying HUD.
DEF HUD_SCY EQU -$30

; Height of the platform.
DEF PLATFORM_HEIGHT EQU $18

; Resting position of platform when not in use
DEF PLATFORM_DISABLE EQU SCRN_Y + 1

; Platform scroll position
DEF PLATFORM_SCY EQU -$18

; Background SCX when offscreen
DEF BACKGROUND_OFFSCREEN_SCX EQU SCRN_X + 5
